# msg_maps.py

# NGAP message mapping: procedureCode -> message name
ngap_msg_map = {
    0: 'AMFConfigurationUpdate',
    1: 'AMFStatusIndication',
    2: 'CellTrafficTrace',
    3: 'DeactivateTrace',
    4: 'DownlinkNASTransport',
    5: 'DownlinkNonUEAssociatedNRPPaTransport',
    6: 'DownlinkRANConfigurationTransfer',
    7: 'DownlinkRANStatusTransfer',
    8: 'DownlinkUEAssociatedNRPPaTransport',
    9: 'ErrorIndication',
    10: 'HandoverCancel',
    11: 'HandoverNotification',
    12: 'HandoverPreparation',
    13: 'HandoverResourceAllocation',
    14: 'InitialContextSetup',
    15: 'InitialUEMessage',
    16: 'LocationReportingControl',
    17: 'LocationReportingFailureIndication',
    18: 'LocationReport',
    19: 'NASNonDeliveryIndication',
    20: 'NGReset',
    21: 'NGSetup',
    22: 'OverloadStart',
    23: 'OverloadStop',
    24: 'Paging',
    25: 'PathSwitchRequest',
    26: 'PDUSessionResourceModify',
    27: 'PDUSessionResourceModifyIndication',
    28: 'PDUSessionResourceRelease',
    29: 'PDUSessionResourceSetup',
    30: 'PDUSessionResourceNotify',
    31: 'PrivateMessage',
    32: 'PWSCancel',
    33: 'PWSFailureIndication',
    34: 'PWSRestartIndication',
    35: 'RANConfigurationUpdate',
    36: 'RerouteNASRequest',
    37: 'RRCInactiveTransitionReport',
    38: 'TraceFailureIndication',
    39: 'TraceStart',
    40: 'UEContextModification',
    41: 'UEContextRelease',
    42: 'UEContextReleaseRequest',
    43: 'UERadioCapabilityCheck',
    44: 'UERadioCapabilityInfoIndication',
    45: 'UETNLABindingRelease',
    46: 'UplinkNASTransport',
    47: 'UplinkNonUEAssociatedNRPPaTransport',
    48: 'UplinkRANConfigurationTransfer',
    49: 'UplinkRANStatusTransfer',
    50: 'UplinkUEAssociatedNRPPaTransport',
    51: 'WriteReplaceWarning',
    52: 'SecondaryRATDataUsageReport',
    53: 'UplinkRIMInformationTransfer',
    54: 'DownlinkRIMInformationTransfer',
    55: 'RetrieveUEInformation',
    56: 'UEInformationTransfer',
    57: 'RANCPRelocationIndication',
    58: 'UEContextResume',
    59: 'UEContextSuspend',
    60: 'UERadioCapabilityIDMapping',
    61: 'HandoverSuccess',
    62: 'UplinkRANEarlyStatusTransfer',
    63: 'DownlinkRANEarlyStatusTransfer',
    64: 'AMFCPRelocationIndication',
    65: 'ConnectionEstablishmentIndication',
    66: 'BroadcastSessionModification',
    67: 'BroadcastSessionRelease',
    68: 'BroadcastSessionSetup',
    69: 'DistributionSetup',
    70: 'DistributionRelease',
    71: 'MulticastSessionActivation',
    72: 'MulticastSessionDeactivation',
    73: 'MulticastSessionUpdate',
    74: 'MulticastGroupPaging',
    75: 'BroadcastSessionReleaseRequired',
    76: 'TimingSynchronisationStatus',
    77: 'TimingSynchronisationStatusReport',
    78: 'MTCommunicationHandling',
    79: 'RANPagingRequest',
    80: 'BroadcastSessionTransport'
}

# NAS message mapping: message type code -> message name
nas_msg_map = {
    0x41: 'Registration Request',
    0x42: 'Registration Accept',
    0x43: 'Registration Complete',
    0x44: 'Registration Reject',
    0x45: 'Deregistration Request',
    0x46: 'Deregistration Accept',
    0x47: 'Deregistration Request (UE Terminated)',
    0x48: 'Deregistration Accept (UE Terminated)',
    0x4C: 'Service Request',
    0x4D: 'Service Reject',
    0x4E: 'Service Accept',
    0x4F: 'Control Plane Service Request',
    0x50: 'Network Slice-Specific Authentication Command',
    0x51: 'Network Slice-Specific Authentication Complete',
    0x52: 'Network Slice-Specific Authentication Result',
    0x54: 'Configuration Update Command',
    0x55: 'Configuration Update Complete',
    0x56: 'Authentication Request',
    0x57: 'Authentication Response',
    0x58: 'Authentication Reject',
    0x59: 'Authentication Failure',
    0x5A: 'Authentication Result',
    0x5B: 'Identity Request',
    0x5C: 'Identity Response',
    0x5D: 'Security Mode Command',
    0x5E: 'Security Mode Complete',
    0x5F: 'Security Mode Reject',
    0x64: '5GMM Status',
    0x65: 'Notification',
    0x66: 'Notification Response',
    0x67: 'UL NAS Transport',
    0x68: 'DL NAS Transport',
    0xC1: 'PDU Session Establishment Request',
    0xC2: 'PDU Session Establishment Accept',
    0xC3: 'PDU Session Establishment Reject',
    0xC5: 'PDU Session Authentication Command',
    0xC6: 'PDU Session Authentication Complete',
    0xC7: 'PDU Session Authentication Result',
    0xC9: 'PDU Session Modification Request',
    0xCA: 'PDU Session Modification Reject',
    0xCB: 'PDU Session Modification Command',
    0xCC: 'PDU Session Modification Complete',
    0xCD: 'PDU Session Modification Command Reject',
    0xD1: 'PDU Session Release Request',
    0xD2: 'PDU Session Release Reject',
    0xD3: 'PDU Session Release Command',
    0xD4: 'PDU Session Release Complete',
    0xD5: '5GSM Status'
}

# Simplified message mapping: full name -> abbreviation
MSG_MAPPING = {
    # ===== NGAP =====
    "AMFConfigurationUpdate": "amf_cfg_upd",
    "AMFStatusIndication": "amf_status_ind",
    "CellTrafficTrace": "cell_traffic_trace",
    "DeactivateTrace": "deact_trace",
    "DownlinkNASTransport": "dl_nas_trans",
    "DownlinkNonUEAssociatedNRPPaTransport": "dl_non_ue_assoc_nrppa_trans",
    "DownlinkRANConfigurationTransfer": "dl_ran_cfg_trans",
    "DownlinkRANStatusTransfer": "dl_ran_status_trans",
    "DownlinkUEAssociatedNRPPaTransport": "dl_ue_assoc_nrppa_trans",
    "ErrorIndication": "err_ind",
    "HandoverCancel": "ho_cancel",
    "HandoverNotification": "ho_notif",
    "HandoverPreparation": "ho_prep",
    "HandoverResourceAllocation": "ho_res_alloc",
    "InitialContextSetup": "init_ctx_setup",
    "InitialUEMessage": "ini_ue_mes",
    "LocationReportingControl": "loc_rpt_ctrl",
    "LocationReportingFailureIndication": "loc_rpt_fail_ind",
    "LocationReport": "loc_report",
    "NASNonDeliveryIndication": "nas_non_deliv_ind",
    "NGReset": "ng_reset",
    "NGSetup": "ng_setup",
    "OverloadStart": "overload_start",
    "OverloadStop": "overload_stop",
    "Paging": "pg",
    "PathSwitchRequest": "path_switch_req",
    "PDUSessionResourceModify": "pdu_sess_res_mod",
    "PDUSessionResourceModifyIndication": "pdu_sess_res_mod_ind",
    "PDUSessionResourceRelease": "pdu_sess_res_rel",
    "PDUSessionResourceSetup": "pdu_sess_res_setup",
    "PDUSessionResourceNotify": "pdu_sess_res_notif",
    "PrivateMessage": "private_msg",
    "PWSCancel": "pws_cancel",
    "PWSFailureIndication": "pws_fail_ind",
    "PWSRestartIndication": "pws_restart_ind",
    "RANConfigurationUpdate": "ran_cfg_upd",
    "RANCPRelocationIndication": "ran_cp_reloc_ind",
    "RANPagingRequest": "ran_pg_req",
    "RRCInactiveTransitionReport": "rrc_inactive_trans_rpt",
    "RerouteNASRequest": "reroute_nas_req",
    "RetrieveUEInformation": "retr_ue_info",
    "SecondaryRATDataUsageReport": "sec_rat_data_usage_rpt",
    "TraceFailureIndication": "trace_fail_ind",
    "TraceStart": "trace_start",
    "UEContextModification": "ue_ctx_mod",
    "UEContextRelease": "ue_ctx_rel",
    "UEContextReleaseRequest": "ue_ctx_rel_req",
    "UERadioCapabilityCheck": "ue_radio_cap_chk",
    "UERadioCapabilityInfoIndication": "ue_radio_cap_info_ind",
    "UETNLABindingRelease": "ue_tnla_bind_rel",
    "UplinkNASTransport": "ul_nas_trans",
    "UplinkNonUEAssociatedNRPPaTransport": "ul_non_ue_assoc_nrppa_trans",
    "UplinkRANConfigurationTransfer": "ul_ran_cfg_trans",
    "UplinkRANEarlyStatusTransfer": "ul_ran_early_status_trans",
    "UplinkRANStatusTransfer": "ul_ran_status_trans",
    "UplinkRIMInformationTransfer": "ul_rim_info_trans",
    "UplinkUEAssociatedNRPPaTransport": "ul_ue_assoc_nrppa_trans",

    # ===== NAS-MM =====
    "Registration Request": "reg_req",
    "Registration Accept": "reg_acc",
    "Registration Complete": "reg_comp",
    "Registration Reject": "reg_rej",
    "Deregistration Request": "dereg_req",
    "Deregistration Accept": "dereg_acc",
    "Deregistration Request (UE Terminated)": "dereg_req",
    "Deregistration Accept (UE Terminated)": "dereg_acc",
    "Service Request": "srv_req",
    "Service Reject": "srv_rej",
    "Service Accept": "srv_acc",
    "Control Plane Service Request": "ctrl_plane_srv_req",
    "Network Slice-Specific Authentication Command": "nssai_auth_cmd",
    "Network Slice-Specific Authentication Complete": "nssai_auth_comp",
    "Network Slice-Specific Authentication Result": "nssai_auth_res",
    "Configuration Update Command": "cfg_upd_cmd",
    "Configuration Update Complete": "cfg_upd_comp",
    "Authentication Request": "auth_req",
    "Authentication Response": "auth_res",
    "Authentication Reject": "auth_rej",
    "Authentication Failure": "auth_fail",
    "Authentication Result": "auth_res",
    "Identity Request": "id_req",
    "Identity Response": "id_res",
    "Security Mode Command": "sec_mode_cmd",
    "Security Mode Complete": "sec_mode_comp",
    "Security Mode Reject": "sec_mode_rej",
    "5GMM Status": "5gmm_status",
    "Notification": "notif",
    "Notification Response": "notif_res",
    "DL NAS Transport": "dl_nas_trans",
    "UL NAS Transport": "ul_nas_trans",

    # ===== NAS-SM =====
    "PDU Session Establishment Request": "pdu_sess_est_req",
    "PDU Session Establishment Accept": "pdu_sess_est_acc",
    "PDU Session Establishment Reject": "pdu_sess_est_rej",
    "PDU Session Authentication Command": "pdu_auth_cmd",
    "PDU Session Authentication Complete": "pdu_auth_comp",
    "PDU Session Authentication Result": "pdu_auth_res",
    "PDU Session Modification Request": "pdu_mod_req",
    "PDU Session Modification Reject": "pdu_mod_rej",
    "PDU Session Modification Command": "pdu_mod_cmd",
    "PDU Session Modification Complete": "pdu_mod_comp",
    "PDU Session Modification Command Reject": "pdu_mod_cmd_rej",
    "PDU Session Release Request": "pdu_rel_req",
    "PDU Session Release Reject": "pdu_rel_rej",
    "PDU Session Release Command": "pdu_rel_cmd",
    "PDU Session Release Complete": "pdu_rel_comp",
    "5GSM Status": "5gsm_status"
    
}


SUFFIX_ABBR = {
    'Request': 'req',
    'Response': 'res',
    'Command': 'cmd',
    'Indication': 'ind',
    'Accept': 'acc',
    'Reject': 'rej',
    'Failure': 'failure',
    'Complete': 'comp',
}


def get_abbreviation(full_name):
    """
    返回完整消息名称对应的缩写：
    1. 优先查找 MSG_MAPPING
    2. 自动处理常见后缀（Request/Response/Command/Indication/...）
    3. 回退为小写下划线形式
    """
    # 1. 直接映射
    if full_name in MSG_MAPPING:
        return MSG_MAPPING[full_name]

    # 2. 后缀处理
    for suffix, suf_abbr in SUFFIX_ABBR.items():
        if full_name.endswith(suffix):
            base = full_name[:-len(suffix)].strip()
            # 如果基本名在映射表中
            if base in MSG_MAPPING:
                return f"{MSG_MAPPING[base]}_{suf_abbr}"
            # 否则递归缩写基本名
            base_simple = base.lower().replace(' ', '_')
            return f"{base_simple}_{suf_abbr}"

    # 3. 通用回退
    return full_name.lower().replace(' ', '_').replace('(', '').replace(')', '')

